[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

board_build.partitions = partitions.csv

lib_deps =
    cyijun/ESP32MQTTClient
    bblanchon/ArduinoJson@^7

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -Os
